gazebo_ros_control:
  pid_gains:
    front_left_wheel_joint: {p: 100.0, i: 0.01, d: 10.0}
    front_right_wheel_joint: {p: 100.0, i: 0.01, d: 10.0}
    
    rear_left_wheel_joint: {p: 100.0, i: 0.01, d: 10.0}
    rear_right_wheel_joint: {p: 100.0, i: 0.01, d: 10.0}
    
    # left_arm_shoulder_pan_joint: {p: 100.0, i: 0.01, d: 10.0}
    # left_arm_shoulder_lift_joint: {p: 100.0, i: 0.01, d: 10.0}
    # left_arm_elbow_joint: {p: 100.0, i: 0.01, d: 10.0}
    # left_arm_wrist_1_joint: {p: 100.0, i: 0.01, d: 10.0}
    # left_arm_wrist_2_joint: {p: 100.0, i: 0.01, d: 10.0}
    # left_arm_wrist_3_joint: {p: 100.0, i: 0.01, d: 10.0}
    
    # right_arm_shoulder_pan_joint: {p: 100.0, i: 0.01, d: 10.0}
    # right_arm_shoulder_lift_joint: {p: 100.0, i: 0.01, d: 10.0}
    # right_arm_elbow_joint: {p: 100.0, i: 0.01, d: 10.0}
    # right_arm_wrist_1_joint: {p: 100.0, i: 0.01, d: 10.0}
    # right_arm_wrist_2_joint: {p: 100.0, i: 0.01, d: 10.0}
    # right_arm_wrist_3_joint: {p: 100.0, i: 0.01, d: 10.0}
