base_link: 'base_link'

left_gripper:
  end_effector_name: 'left_gripper'
  end_effector_type: 'finger'

  # actuated joints in the end effector
  joints: [
    'left_gripper_palm_finger_1_joint', 
    'left_gripper_palm_finger_2_joint',
    'left_gripper_finger_1_joint_proximal_actuating_hinge',
    'left_gripper_finger_2_joint_proximal_actuating_hinge',
    'left_gripper_finger_middle_joint_proximal_actuating_hinge',
    'left_gripper_finger_1_joint_2',
    'left_gripper_finger_1_joint_3',
    'left_gripper_finger_2_joint_2',
    'left_gripper_finger_2_joint_3',
    'left_gripper_palm_finger_middle_joint',
    'left_gripper_finger_middle_joint_2',
    'left_gripper_finger_middle_joint_3',
  ]

  pregrasp_time_from_start: 0.0   # time to wait before acting pregrasp posture
  grasp_time_from_start: 0.0      # time to wait before acting grasp posture

  # width of gripper fingers
  gripper_finger_width: 0.015

  # max object width that can fit between fingers
  max_grasp_width: 0.08

  # x/y and angle grasp resolution parameters (angle is in degrees)
  grasp_resolution: 0.05
  angle_resolution: 90

  # max/min depth of fingers (distance from finger tip to inner palm)
  grasp_max_depth: 0.035
  grasp_min_depth: 0.01
  grasp_depth_resolution: 1.05

  # length of approach path (this is in addition to grasp_max_depth)
  approach_distance_desired: 0.1

  # length of retreat path (this is in addition to grasp_max_depth)
  retreat_distance_desired: 0.1

  # minimum distance to lift object after grasping
  lift_distance_desired: 0.01

  # open position
  pregrasp_posture: [
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0
  ]

  # close position
  grasp_posture: [
    0.0, 
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0
  ]

  #  Distance from the eef mount to the palm of end effector [x, y, z, r, p, y]
  # z-axis pointing toward object to grasp
  # x-axis perp. to movement of grippers
  # y-axis parallel to movement of grippers
  # grasp_pose_to_eef_transform :  [0, 0, -0.065, -1.5708, 0, 2.3562] # NOTE: Imaginary point in the middle
  grasp_pose_to_eef_transform :  [0, 0, -0.2445, 0, 0, 2.3562] # NOTE: Imaginary point in the middle
  # distance = 0.092 + 0.065 + 0.0875 = 0.2445

  # minimum padding on each side of the object on approach
  grasp_padding_on_approach: 0.005

  # Distance between fingers
  max_finger_width: 0.085
  min_finger_width: 0.06
