# The name of this file shouldn't be changed, or else the Setup Assistant won't detect it
sensors: 
  # - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
  #   point_cloud_topic: left_gripper_sensor_d415_camera/depth_registered/points
  #   # point_cloud_topic: left_gripper_sensor_d415_camera/depth_registered
  #   max_range: 3.0
  #   point_subsample: 1
  #   padding_offset: 0.1
  #   padding_scale: 1.0
  #   filtered_cloud_topic: filtered_cloud
  # - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
  #   point_cloud_topic: right_gripper_sensor_d415_camera/depth_registered/points
  #   # point_cloud_topic: right_gripper_sensor_d415_camera/depth_registered
  #   max_range: 3.0
  #   point_subsample: 1
  #   padding_offset: 0.1
  #   padding_scale: 1.0
  #   filtered_cloud_topic: filtered_cloud
  - sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
    image_topic: /left_gripper_sensor_d415_camera/aligned_depth_to_color/image_raw
    queue_size: 1 # 1
    near_clipping_plane_distance: 0.01
    far_clipping_plane_distance: 2.00 # 3.00 - 5.00
    shadow_threshold: 0.2 # 0.2
    padding_scale: 1.0
    padding_offset: 0.01
    max_update_rate: 0.5
    filtered_cloud_topic: filtered_cloud
  - sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
    image_topic: /right_gripper_sensor_d415_camera/aligned_depth_to_color/image_raw
    queue_size: 1 # 1
    near_clipping_plane_distance: 0.01
    far_clipping_plane_distance: 2.00 # 3.00 - 5.00
    shadow_threshold: 0.2 # 0.2
    padding_scale: 1.0
    padding_offset: 0.01
    max_update_rate: 0.5
    filtered_cloud_topic: filtered_cloud
