<?xml version="1.0"?>
<robot name="bulldog_robot" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find bulldog_description)/urdf/accessories/wheel.urdf.xacro" />
  <xacro:include filename="$(find bulldog_description)/urdf/accessories/materials.urdf.xacro" />
  <xacro:include filename="$(find bulldog_description)/urdf/accessories/plates.urdf.xacro" />
  <xacro:include filename="$(find bulldog_description)/urdf/accessories/realsense_support.urdf.xacro" />
  <xacro:include filename="$(find ur_description)/urdf/ur5.urdf.xacro" />
  <xacro:include filename="$(find lms1xx)/urdf/sick_lms1xx.urdf.xacro" />
  <xacro:include filename="$(find robotiq_3f_gripper_visualization)/cfg/robotiq_hand_macro.urdf.xacro" />
  <xacro:include filename="$(find bulldog_description)/urdf/sensors/kinect_camera.urdf.xacro" />
  <xacro:include filename="$(find realsense2_description)/urdf/_d415.urdf.xacro" />

  <!-- Base Size -->
  <xacro:property name="base_x_size" value="0.85000000" />
  <xacro:property name="base_y_size" value="0.42000000" />
  <xacro:property name="base_z_size" value="0.32500000" />

  <!-- Wheel Mounting Positions -->
  <xacro:property name="wheelbase" value="0.5587" /> <!-- husky = 0.5120 -->
  <xacro:property name="track" value="0.5708" /> <!-- husky = 0.5708 -->
  <xacro:property name="wheel_vertical_offset" value="0.04352" /> <!-- husky = 0.3282 -->

  <!-- Wheel Properties -->
  <xacro:property name="wheel_length" value="0.1420" /> <!-- husky = 0.1143 -->
  <xacro:property name="wheel_radius" value="0.1830" /> <!-- husky = 0.1651 -->

  <!-- IMU Mounting Positions -->
  <xacro:property name="imu_xyz" value="0.19 0 0.149" />
  <xacro:property name="imu_rpy" value="0 -1.5708 3.1416" />

  <!-- Dual UR5 Mounting Positions -->
  <xacro:property name="left_arm_xyz" value="0 0.15945 0.09069" />
  <xacro:property name="left_arm_rpy" value="${-pi / 4} 0 0" />
  <xacro:property name="right_arm_xyz" value="0 -0.15945 0.09069" />
  <xacro:property name="right_arm_rpy" value="${-pi / 4} 0 ${pi}" />

  <!-- Robotiq 3 Finger Gripper Mounting Positions -->
  <xacro:property name="left_robotiq_3f_gripper_xyz" value="0 0 0.065" />
  <xacro:property name="left_robotiq_3f_gripper_rpy" value="${pi / 2} 0 ${-pi * 3 / 4}" />
  <xacro:property name="right_robotiq_3f_gripper_xyz" value="0 0 0.065" />
  <xacro:property name="right_robotiq_3f_gripper_rpy" value="${pi / 2} 0 ${pi * 3 / 4}" />

  <!-- LMS1xx LiDAR Angle Range and Mounting Positions -->
  <xacro:property name="lms1xx_angle" value="${pi * 2 / 4}" />
  <xacro:property name="lms1xx_xyz" value="0.015 0 0.044" />
  <xacro:property name="lms1xx_rpy" value="${pi} 0 0" />

  <!-- Realsense D415 Mounting Positions -->
  <xacro:property name="left_gripper_sensor_support_xyz" value="0 -0.050 0" />
  <xacro:property name="left_gripper_sensor_support_rpy" value="${pi / 2} 0 ${pi}" />
  <xacro:property name="right_gripper_sensor_support_xyz" value="0 -0.050 0" />
  <xacro:property name="right_gripper_sensor_support_rpy" value="${-pi / 2} 0 0" />

  <xacro:macro name="bulldog_robot">
    <!-- Base link is the center of the robot's bottom plate -->
    <link name="base_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://bulldog_description/meshes/base_link.stl" />
        </geometry>
        <material name="flat_black" />
      </visual>
      <collision>
        <origin xyz="0 0 ${base_z_size / 4.0}" rpy="0 0 0" />
        <geometry>
          <box size="${base_x_size} ${base_y_size} ${base_z_size / 2}"/>
        </geometry>
      </collision>
      <!-- <collision>
        <origin xyz="0 0 ${base_z_size * 3 / 4 - 0.01}" rpy="0 0 0" />
        <geometry>
          <box size="${base_x_size * 4 / 5} ${base_y_size} ${base_z_size / 2 - 0.02}"/>
        </geometry>
      </collision> -->
    </link>

    <gazebo reference="base_link">
      <material>Gazebo/FlatBlack</material>
    </gazebo>

    <!-- Base footprint is on the ground under the robot -->
    <link name="base_footprint"/>

    <joint name="base_footprint_joint" type="fixed">
      <origin xyz="0 0 ${wheel_vertical_offset - wheel_radius}" rpy="0 0 0" />
      <parent link="base_link" />
      <child link="base_footprint" />
    </joint>

    <!-- Interial link stores the robot's inertial information -->
    <link name="inertial_link">
      <inertial>
        <mass value="40" />
        <origin xyz="0 0 0.1" />
        <inertia ixx="0.7" ixy="-0.03" ixz="-0.15" iyy="2" iyz="-0.01" izz="4" />
      </inertial>
    </link>

    <!-- Dual UR5 Husky -->
    <!-- <link name="inertial_link">
      <inertial>
        <mass value="48.39054"/>
        <origin xyz="-0.0648 -0.00059 0.07895"/>
        <inertia ixx="2.1634275613800003" ixy="-0.055452352110000006" ixz="-0.41083822026" iyy="3.5314689495400002" iyz="-0.004366145530000001" izz="4.4759585875" />
      </inertial>
    </link> -->

    <!-- Husky -->
    <!-- <link name="inertial_link">
      <inertial>
        <mass value="46.034" />
        <origin xyz="-0.00065 -0.085 0.062" />
        <inertia ixx="0.6022" ixy="-0.02364" ixz="-0.1197" iyy="1.7386" iyz="-0.001544" izz="2.0296" />
      </inertial>
    </link> -->

    <joint name="inertial_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <parent link="base_link" />
      <child link="inertial_link" />
    </joint>

    <!-- IMU link is the standard mounting position for the UM6 IMU.-->
    <!-- Can be modified with environment variables in /etc/ros/setup.bash -->
    <link name="imu_link"/>
    <joint name="imu_joint" type="fixed">
      <origin xyz="${imu_xyz}" rpy="${imu_rpy}" />
      <parent link="base_link" />
      <child link="imu_link" />
    </joint>
    <gazebo reference="imu_link" />

    <!-- Wheel macros -->
    <xacro:bulldog_wheel wheel_prefix="front_left" wheel_length="${wheel_length}" wheel_radius="${wheel_radius}">
      <origin xyz="${wheelbase / 2} ${track / 2} ${wheel_vertical_offset}" rpy="0 0 0" />
    </xacro:bulldog_wheel>
    <xacro:bulldog_wheel wheel_prefix="front_right" wheel_length="${wheel_length}" wheel_radius="${wheel_radius}">
      <origin xyz="${wheelbase / 2} ${-track / 2} ${wheel_vertical_offset}" rpy="0 0 0" />
    </xacro:bulldog_wheel>
    <xacro:bulldog_wheel wheel_prefix="rear_left" wheel_length="${wheel_length}" wheel_radius="${wheel_radius}">
      <origin xyz="${-wheelbase / 2} ${track / 2} ${wheel_vertical_offset}" rpy="0 0 0" />
    </xacro:bulldog_wheel>
    <xacro:bulldog_wheel wheel_prefix="rear_right" wheel_length="${wheel_length}" wheel_radius="${wheel_radius}">
      <origin xyz="${-wheelbase / 2} ${-track / 2} ${wheel_vertical_offset}" rpy="0 0 0" />
    </xacro:bulldog_wheel>

    <!-- Top plate -->
    <xacro:top_plate />

    <!-- Installation plate -->
    <xacro:installation_plate />

    <!-- Dual UR5 Arms -->
    <xacro:if value="$(arg dual_ur5_enabled)">
      <xacro:ur5_robot prefix="left_arm_" joint_limited="true"
        transmission_hw_interface="hardware_interface/PositionJointInterface" />
      <joint name="left_arm_base" type="fixed">
        <parent link="installation_plate_link" />
        <child link="left_arm_base_link" />
        <origin xyz="${left_arm_xyz}" rpy="${left_arm_rpy}" />
      </joint>
      
      <xacro:ur5_robot prefix="right_arm_" joint_limited="true"
        transmission_hw_interface="hardware_interface/PositionJointInterface" />
      <joint name="right_arm_base" type="fixed">
        <parent link="installation_plate_link" />
        <child link="right_arm_base_link" />
        <origin xyz="${right_arm_xyz}" rpy="${right_arm_rpy}" />
      </joint>

      <!-- If you modify the name of the grippers, remember to change the *prefix* in line 
           780 and 782 accordingly of $(find robotiq_3f_gripper_articulated_gazebo_plugins)/src/RobotiqHandPlugin.cpp. -->
      <xacro:robotiq_hand prefix="left_gripper_" parent="left_arm_tool0" reflect="-1">
        <origin xyz="${left_robotiq_3f_gripper_xyz}" rpy="${left_robotiq_3f_gripper_rpy}" />
      </xacro:robotiq_hand>

      <xacro:robotiq_hand prefix="right_gripper_" parent="right_arm_tool0" reflect="-1">
        <origin xyz="${right_robotiq_3f_gripper_xyz}" rpy="${right_robotiq_3f_gripper_rpy}" />
      </xacro:robotiq_hand>

    </xacro:if>

    <!-- Sick LMS1xx LiDAR -->
    <xacro:if value="$(arg laser_enabled)">
      <xacro:laser_plate />
      <sick_lms1xx frame="laser" topic="scan" visualize="true" 
        min_angle="${-lms1xx_angle}" max_angle="${lms1xx_angle}"/>
      <joint name="laser_mount_joint" type="fixed">
        <origin xyz="${lms1xx_xyz}" rpy="${lms1xx_rpy}" />
        <parent link="laser_plate_link" />
        <child link="laser" />
      </joint>
    </xacro:if>

    <!-- Kinect -->
    <xacro:if value="$(arg kinect_enabled)">
      <xacro:kinect_camera prefix="kinect" parent="installation_plate_link" />
    </xacro:if>

    <!-- RealSense D415 -->
    <xacro:if value="$(arg realsense_enabled)">
      <xacro:realsense_support prefix="left_gripper_sensor_support_" 
        installation_link="left_gripper_palm">
        <origin xyz="${left_gripper_sensor_support_xyz}" rpy="${left_gripper_sensor_support_rpy}" />
      </xacro:realsense_support>

      <xacro:sensor_d415 prefix="left_gripper_sensor_d415_" 
        parent="left_gripper_sensor_support_mounted_link">
        <origin xyz="0 0 0" rpy="0 0 0"/>
      </xacro:sensor_d415>

      <xacro:realsense_support prefix="right_gripper_sensor_support_" 
        installation_link="right_gripper_palm">
        <origin xyz="${right_gripper_sensor_support_xyz}" rpy="${right_gripper_sensor_support_rpy}" />
      </xacro:realsense_support>

      <xacro:sensor_d415 prefix="right_gripper_sensor_d415_" 
        parent="right_gripper_sensor_support_mounted_link">
        <origin xyz="0 0 0" rpy="0 0 0"/>
      </xacro:sensor_d415>
    </xacro:if>
  </xacro:macro>

</robot>
