# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  shoulder_pan_joint:
    has_velocity_limits: true
    max_velocity: 1.575 # 3.15 / 2
    has_acceleration_limits: true
    max_acceleration: 1.575
  shoulder_lift_joint:
    has_velocity_limits: true
    max_velocity: 1.575
    has_acceleration_limits: true
    max_acceleration: 1.575
  elbow_joint:
    has_velocity_limits: true
    max_velocity: 1.575
    has_acceleration_limits: true
    max_acceleration: 1.575
  wrist_1_joint:
    has_velocity_limits: true
    max_velocity: 1.6 # 3.2 / 2
    has_acceleration_limits: true
    max_acceleration: 1.6
  wrist_2_joint:
    has_velocity_limits: true
    max_velocity: 1.6
    has_acceleration_limits: true
    max_acceleration: 1.6
  wrist_3_joint:
    has_velocity_limits: true
    max_velocity: 1.6
    has_acceleration_limits: true
    max_acceleration: 1.6