# Settings for ros_control control loop
hardware_control_loop:
   loop_hz: 125

# Settings for ros_control hardware interface
hardware_interface:
   joints:
     - shoulder_pan_joint
     - shoulder_lift_joint
     - elbow_joint
     - wrist_1_joint
     - wrist_2_joint
     - wrist_3_joint

# Publish all joint states ----------------------------------
joint_state_controller:
   type:         joint_state_controller/JointStateController
   publish_rate: 125

# Publish wrench ----------------------------------
force_torque_sensor_controller:
   type:         force_torque_sensor_controller/ForceTorqueSensorController
   publish_rate: 125

# Joint Trajectory Controller - position based -------------------------------
# For detailed explanations of parameter see http://wiki.ros.org/joint_trajectory_controller
arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - shoulder_pan_joint
     - shoulder_lift_joint
     - elbow_joint
     - wrist_1_joint
     - wrist_2_joint
     - wrist_3_joint
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
      shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
      elbow_joint: {trajectory: 0.1, goal: 0.1}
      wrist_1_joint: {trajectory: 0.1, goal: 0.1}
      wrist_2_joint: {trajectory: 0.1, goal: 0.1}
      wrist_3_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate: 25
  action_monitor_rate: 10

left_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - left_arm_shoulder_pan_joint
     - left_arm_shoulder_lift_joint
     - left_arm_elbow_joint
     - left_arm_wrist_1_joint
     - left_arm_wrist_2_joint
     - left_arm_wrist_3_joint
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      left_arm_shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
      left_arm_shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
      left_arm_elbow_joint: {trajectory: 0.1, goal: 0.1}
      left_arm_wrist_1_joint: {trajectory: 0.1, goal: 0.1}
      left_arm_wrist_2_joint: {trajectory: 0.1, goal: 0.1}
      left_arm_wrist_3_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate: 25
  action_monitor_rate: 10

right_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - right_arm_shoulder_pan_joint
     - right_arm_shoulder_lift_joint
     - right_arm_elbow_joint
     - right_arm_wrist_1_joint
     - right_arm_wrist_2_joint
     - right_arm_wrist_3_joint
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      right_arm_shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
      right_arm_shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
      right_arm_elbow_joint: {trajectory: 0.1, goal: 0.1}
      right_arm_wrist_1_joint: {trajectory: 0.1, goal: 0.1}
      right_arm_wrist_2_joint: {trajectory: 0.1, goal: 0.1}
      right_arm_wrist_3_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate: 25
  action_monitor_rate: 10
