<?xml version="1.0"?>
<robot name="bulldog_robot" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find bulldog_description)/urdf/accessories/wheel.urdf.xacro" />
  <xacro:include filename="$(find bulldog_description)/urdf/accessories/materials.urdf.xacro" />
  <xacro:include filename="$(find bulldog_description)/urdf/accessories/plates.urdf.xacro" />
  <xacro:include filename="$(find ur_description)/urdf/ur5.urdf.xacro" />
  <xacro:include filename="$(find lms1xx)/urdf/sick_lms1xx.urdf.xacro" />
  <xacro:include filename="$(find robotiq_3f_gripper_visualization)/cfg/robotiq_hand_macro.urdf.xacro" />
  <xacro:include filename="$(find bulldog_description)/urdf/sensors/kinect_camera.urdf.xacro" />

  <xacro:property name="wheel_length" value="0.142" />
  <xacro:property name="wheel_radius" value="0.183" />

  <xacro:property name="base_x_size" value="0.85" />
  <xacro:property name="base_y_size" value="0.42" />
  <xacro:property name="base_z_size" value="0.325" />

  <xacro:macro name="bulldog_robot">

    <!-- base -->
    <link name="base_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://bulldog_description/meshes/base_link.stl" />
        </geometry>
        <material name="flat_black" />
      </visual>
      <collision>
        <origin xyz="0 0 ${base_z_size / 2.0}" rpy="0 0 0" />
        <geometry>
          <box size="${base_x_size} ${base_y_size} ${base_z_size}"/>
        </geometry>
      </collision>
    </link>

    <gazebo reference="base_link">
      <material>Gazebo/FlatBlack</material>
    </gazebo>

    <!-- inertial -->
    <link name="inertial_link">
      <inertial>
        <mass value="40" />
        <origin xyz="0 0 0.1" />
        <inertia ixx="0.7" ixy="-0.03" ixz="-0.15" iyy="2" iyz="-0.01" izz="4" />
      </inertial>
    </link>

    <joint name="inertial_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <parent link="base_link" />
      <child link="inertial_link" />
    </joint>

    <!-- top plate -->
    <xacro:top_plate />

    <!-- imu -->
    <link name="imu_link"/>

    <joint name="imu_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <parent link="base_link" />
      <child link="imu_link" />
    </joint>

    <gazebo reference="imu_link" />

    <xacro:bulldog_wheel wheel_prefix="front_left">
      <origin xyz="0.27937 0.285 0.0435" rpy="0 0 0" />
    </xacro:bulldog_wheel>
    <xacro:bulldog_wheel wheel_prefix="front_right">
      <origin xyz="0.27937 -0.285 0.0435" rpy="0 0 0" />
    </xacro:bulldog_wheel>
    <xacro:bulldog_wheel wheel_prefix="rear_left">
      <origin xyz="-0.27937 0.285 0.0435" rpy="0 0 0" />
    </xacro:bulldog_wheel>
    <xacro:bulldog_wheel wheel_prefix="rear_right">
      <origin xyz="-0.27937 -0.285 0.0435" rpy="0 0 0" />
    </xacro:bulldog_wheel>

    <!-- installation plate -->
    <xacro:installation_plate />

    <!-- dual ur5 arms -->
    <xacro:if value="$(arg dual_ur5_enabled)">
      <xacro:ur5_robot prefix="left_arm_" joint_limited="true"/>    
      <joint name="left_arm_base" type="fixed">
        <parent link="installation_plate_link" />
        <child link="left_arm_base_link" />
        <origin xyz="0 0.15945 0.09069" rpy="-0.785 0 0" />
      </joint>
      
      <xacro:ur5_robot prefix="right_arm_" joint_limited="true"/>  
      <joint name="right_arm_base" type="fixed">
        <parent link="installation_plate_link" />
        <child link="right_arm_base_link" />
        <origin xyz="0 -0.15945 0.09069" rpy="-0.785 0 ${pi}" />
      </joint>

      <xacro:robotiq_hand prefix="l_" parent="left_arm_ee_link" reflect="-1">
        <origin rpy="0 0 -1.57" xyz="0 0 0"/>
      </xacro:robotiq_hand>
      <xacro:robotiq_hand prefix="r_" parent="right_arm_ee_link" reflect="-1">
        <origin rpy="0 0 -1.57" xyz="0 0 0"/>
      </xacro:robotiq_hand>
    </xacro:if>

    <!-- laser -->
    <xacro:if value="$(arg laser_enabled)">
      <xacro:laser_plate />
      <sick_lms1xx frame="laser" topic="scan"/>
      <joint name="laser_mount_joint" type="fixed">
        <origin xyz="0.015 0 0.044" rpy="${pi} 0 0" />
        <parent link="laser_plate_link" />
        <child link="laser" />
      </joint>
    </xacro:if>

    <!-- kinect -->
    <xacro:if value="$(arg kinect_enabled)">
      <xacro:kinect_camera />
    </xacro:if>

  </xacro:macro>

</robot>
